# Generated by Django 4.1.1 on 2023-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_snippet_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
